config/routes.rb
GifVault::Application.routes.draw do

  get 'developers/home'

  resources :ideas

  #root to: 'gif#cool'
  root to: 'ideas#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/cool' => 'gif#cool'  
  get '/sweet' => 'gif#sweet'
  
  get '/ideas' => 'ideas#new'
  post '/ideas' => 'ideas#create'
  get '/ideas' => 'ideas#destroy'  
  
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  validates :idea_description, :idea_benefit, :email, :supervisor_email, :presence=>true
  validates_format_of :email, :with => /@/
  validates_format_of :supervisor_email, :with => /@/
  enum idea_status: [:Open, :Implemented, :Rejected]
  enum priority: [:Low, :Medium, :High]
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def home
  end
end

app/controllers/gif_controller.rb
class GifController < ApplicationController

  before_filter :authorize

  def cool
  end

  def sweet
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  before_action :all_ideas, only: [:index, :create, :destroy, :update]
  before_filter :authorize
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :set_priorities
  before_action :set_idea_statuses
  
  respond_to :html, :js
  
  # GET /ideas
  # GET /ideas.json
  def index
    # @ideas = Idea.all   
    @ideas = Idea.where("email = ? OR supervisor_email = ?", session[:email], session[:email])
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end
  
  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
	@idea.save!
	@current_idea = @idea
	@ideas = Idea.where("email = ? OR supervisor_email = ?", session[:email], session[:email]) 
	# Send email
	UserMailer.send_email(@idea).deliver
  end

  def update
    @idea.update!(idea_params)
    @current_idea = @idea
	@ideas = Idea.where("email = ? OR supervisor_email = ?", session[:email], session[:email])
	# Send email
	UserMailer.send_email(@idea).deliver

  end

  def destroy
    @idea.destroy!
    @current_idea = @idea
	@ideas = Idea.where("email = ? OR supervisor_email = ?", session[:email], session[:email])
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

	def set_priorities
		@priorities = Idea.priorities
	end

	def set_idea_statuses
		@idea_statuses = Idea.idea_statuses
	end	 
	
    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:idea_description, :idea_benefit, :priority, :idea_status, :email, :supervisor_email)
    end
    
    def idea_emails
      params.require(:idea).permit(:email)
    end
    
    def all_ideas
      @ideas = Idea.all
    end	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # if the user exists AND the password entered is correct
    if user && user.authenticate(params[:password])
      # save the user id inside the browser cookie. This is how we keep the user logged in when they navigate around our website.
      session[:user_id] = user.id
      session[:email] = user.email
      session[:supervisor_email] = user.supervisor_email
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    session[:email] = nil
    session[:supervisor_email] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      session[:email] = user.email
      session[:supervisor_email] = user.supervisor_email      
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:supervisor_email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/developers/home.html.erb
<div>
	<strong>CIS 658  - Project Proposal</strong><br>
	<strong>Ehsan Rahman</strong>
</div>
<div>
	<br>
	<p>
	"Suggestion Box" Application is a web based application, encourage employees to submit ideas and suggestions. Company can gather ideas for problems that have the highest business value with this application. Employee can express their ideas related to cost reduction, better way of increase employee productivities, idea on how to improve processes and many more.
	<br><br>
	<strong>Backend:</strong>
	All data will be store at Rails sqllite database.
	</p>
</div>
<div>
	<strong>Add/Maintain Suggestions:</strong>
	<ul>
		<strong>Signup Screen:</strong>
		<ul>
			Signup screen consists of employee full name, email address, password and supervisor email address.
			<li>User can create username and password for the application</li>
			<li>User must enter supervisor email address for notification</li>
		</ul>
		<br>
		<strong>Login:</strong>
		<ul>
			<li>User enters email address</li>
			<li>User enters valid password</li>
		</ul>
		<br>
		<strong>Logout:</strong>
		<ul>
			<li>Logout flush users credentials</li>
			<li>Redirects to login screen</li>
		</ul>		
		<br>
		<p class="text-info">Suggestion screen consists of email address, supervisor email address, idea_status,  idea_description, Idea_benifit</p>
		<strong>General Users: </strong>
		<ul>
			<li>User logs in to the application using email address</li>
			<li>User can add an idea</li>
			<li>User can edit idea</li>
			<li>User can delete idea</li>
		</ul>
		<br>
		<strong>Supervisor: </strong>
		<ul>
			<li>Supervisor logs in to the application using email address</li>
			<li>Supervisor can add an idea</li>
			<li>Supervisor can edit idea</li>
			<li>Supervisor can delete idea</li>
			<li>Supervisor can view ideas for employees that he or she supervise</li>
			<li>Supervise can accept or reject the idea</li>
		</ul>
	
		<br>
		<strong>Notification:</strong>
		<ul>
			<li>Application will email to user and supervisor after creation of an idea</li>
			<li>Application will notify user for any change of the idea</li>
		</ul>
		<br>
		<strong>Service:</strong>
		<ul>
			<li>Application expose RESTful service for GET and POST</li>
			<li>Service will provide list of all suggestions that are submitted by uses</li>
			<div class="alert alert-info">
				<strong>REST API:</strong><br>
				<strong>URL:</strong><br>
					<ul>Link to <a target="_blank" href="/ideas.json">RESTful Web Service</a></ul><hr>
				<strong>Resource Information:</strong><br>
					<ul>
						<li>Response formats: JSON</li>
						<li>Requires authentication: Yes (user context only)</li>
						<li>Rate limited: Yes </li>
						<li>Requests: 15 minutes windows</li>
					</ul><br><hr>
				<strong>Parameters:</strong><br>
					<ul>None</ul><hr>
				<strong>Example Request (GET):</strong><br>
					<ul>
					[<br>
						<ul>{</ul>
							<ul>"id": 1,<br>
								"idea_description": "Ehsan",<br>
								"idea_benefit": "Rahman",<br>
								"priority": "Low",<br>
								"idea_status": "Open",<br>
								"email": "ehsan.rahman2@gmail.com",<br>
								"supervisor_email": "rahman_ehsan@hotmail.com",<br>
								"url": "http://localhost:3000/ideas/1.json"<br>
							</ul>
						<ul>}</ul>
					]
					</ul><hr>
				<strong>Example Request (POST):</strong><br>
					<ul>{</ul>
						<ul>"idea_description": "Ehsan",<br>
							"idea_benefit": "Rahman",<br>
							"priority": "Low",<br>
							"idea_status": "Open",<br>
							"email": "ehsan.rahman2@gmail.com",<br>
							"supervisor_email": "rahman_ehsan@hotmail.com"<br>
						</ul>
					<ul>}</ul>
					<hr>
			</div>
			
			
		</ul>
	</ul>
	<br>
</div>

app/views/gif/cool.html.erb
<h1>COOL!</h1>

<%= image_tag "http://paulrobertson.mechafetus.com/meowmeow.gif" %>
<br>
<br>
<%= link_to 'Sweet', '/sweet' %>

app/views/gif/sweet.html.erb
<h1>SWEET!</h1>

<%= image_tag "http://paulrobertson.mechafetus.com/expedition.gif" %>
<br>
<br>
<%= link_to 'Cool', '/cool' %>

app/views/ideas/_form.html.erb
<%= form_for(@idea, remote: true) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
	<div class="container">
        <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
        	<div class="panel panel-default">
        		<div class="panel-heading">
			 			</div>
			 			<div class="panel-body">
			    		<form role="form">
							<div class="form-group">
							<%= f.label 'Description:', class: 'col-sm-10 control-label' %>
							<%= f.text_area :idea_description, class: 'form-control' %>
			    			</div>
							<div class="form-group">
								<%= f.label 'Benefit:', class: 'col-sm-10 control-label' %>
			    				<%= f.text_area :idea_benefit, class: 'form-control' %>
			    			</div>
			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<%= f.label 'Priority:', class: 'col-sm-10 control-label' %>
			    						<%= f.select :priority, options_for_select(@priorities.collect {|s| [s[0].humanize, s[0]]}, selected: @idea.priority), {}, class: 'form-control' %>
			    					</div>
			    				</div>
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<%= f.label 'Status:', class: 'col-sm-10 control-label' %>
			    						<%= f.select :idea_status, options_for_select(@idea_statuses.collect {|s| [s[0].humanize, s[0]]}, selected: @idea.idea_status), {}, class: 'form-control' %>
			    					</div>
			    				</div>
			    			</div>
			    			<div class="form-group">
			    				<%= f.label 'User Email:', class: 'col-sm-10 control-label' %>
			    				<input type="text" name="idea[email]" id="idea_email" value=<%= session[:email] %> readonly class="form-control">
			    			</div>		    			
			    			<div class="form-group">
			    				<%= f.label 'Supervisor Email:', class: 'col-sm-10 control-label' %>
			    				<input type="text" name="idea[supervisor_email]" id="idea_supervisor_email" value=<%= session[:supervisor_email] %> readonly class="form-control">
			    			</div>			    			
			    			<input type="submit" name="commit" value="Add/Update Idea" class="btn btn-info btn-block">
			    		
			    		</form>
			    	</div>
	    		</div>
    		</div>
    	</div>
    </div>  

<% end %>

app/views/ideas/_idea.html.erb
 <% if idea == @current_idea %>
	<div id="current_idea" class="article">
<% else %>
	<div class="article">
<% end %>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Description</th>
            <th>Benefit</th>
            <th>Status</th>
			<th>Submit By</th>
			<th>Supervisor</th>
			<th>Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= idea.idea_description %></td>
            <td><%= idea.idea_benefit %></td>
			<td><%= idea.idea_status %></td>
            <td><%= idea.email %></td>
			<td><%= idea.supervisor_email %></td>
			<td> <%= link_to image_tag("edit_icon.jpg", width: '15', height: '15', title: 'Edit'), edit_idea_path(idea), remote: true %> <%= link_to image_tag("delete_icon.jpg", width: '20', height: '20', title: 'Delete'), idea, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
        </tr>
    </tbody>
</table>  
 </div>

app/views/ideas/create.js.erb
$('#ideas').html("<%= j (render @ideas) %>");
$('#blog-form').slideUp(350);

$('#current_idea').css({'background-color' : '#88ff88'}).animate({'background-color' : '#ffffff'}, 1000);

app/views/ideas/destroy.js.erb
$('#ideas').html("<%= j (render @ideas) %>");

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/edit.js.erb
$('#blog-form').html("<%= j (render 'form') %>");
$('#blog-form').slideDown(350);

app/views/ideas/index.html.erb
<button class="btn btn-warning pull-right">
	<%= link_to 'New Idea', new_idea_path, remote: true %>
</button>

<h1>Suggestion list</h1>

<div id="ideas">
	<%= render @ideas %>
</div>

<button class="btn btn-warning pull-right">
	<%= link_to 'New Idea', new_idea_path, remote: true %>
</button>
		
<div id="blog-form" style="display:none;"></div>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/new.js.erb
$('#blog-form').html("<%= j (render 'form') %>");
$('#blog-form').slideDown(350);
if((obj = document.getElementById("submitbutton")) && obj != null){
          window.scrollTo(0, obj.offsetTop);
      }

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Description</th>
            <th>Benefit</th>
            <th>Priority</th>
            <th>Status</th>
			<th>Email</th>
			<th>Supervisor Email</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @idea.idea_description %></td>
            <td><%= @idea.idea_benefit %></td>
            <td><%= @idea.priority %></td>
			<td><%= @idea.idea_status %></td>
            <td><%= @idea.email %></td>
			<td><%= @idea.supervisor_email %></td>
        </tr>
    </tbody>
</table>

<%= link_to 'Edit', edit_idea_path(@idea) , :class => "btn btn-info" %>
<%= link_to 'Back', ideas_path, :class => "btn btn-info" %>

app/views/ideas/update.js.erb
$('#ideas').html("<%= j (render @ideas) %>");
$('#blog-form').slideUp(350);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suggestion Box</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= controller.controller_name %>">
	<%= render 'shared/navigation' %>
	<div class="container theme-showcase" role="main">
		<div id="main">		
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Suggestion Box</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
		<li><a href="/ideas">Ideas</a></li>
		<li><a href="/developers/home">Developers</a></li>        
      </ul>
      <ul class="nav navbar-nav navbar-right">
		<% if current_user %>
			<li><a href="#">Signed in as <%= current_user.name %></a></li>
			<li><%= link_to "Logout", '/logout' %></li>		<% else %>			<li><%= link_to 'Login', '/login' %></li>
		  	<li> <%= link_to 'Signup', '/signup' %></li>		<% end %>		
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/new.html.erb
<%= form_for :user, url: '/users' do |f| %>
	<div class="container">
        <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
        	<div class="panel panel-default">
        		<div class="panel-heading">
			    		<h3 class="panel-title">Please Sign Up <small>It's free!</small></h3>
			 			</div>
			 			<div class="panel-body">
			    		<form role="form">
							<div class="form-group">
			    				<input type="text" name="user[name]" id="user_name" class="form-control input-sm" placeholder="Full Name" required>
			    			</div>
			    			<div class="form-group">
			    				<input type="email" name="user[supervisor_email]" id="user_supervisor_email" class="form-control input-sm" placeholder="Supervisor Email Address" required>
			    			</div>			    			
			    			<div class="form-group">
			    				<input type="email" name="user[email]" id="user_email" class="form-control input-sm" placeholder="Email Address(Account Id)" required>
			    			</div>

			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="password" name="user[password]" id="user_password" class="form-control input-sm" placeholder="Password" required>
			    					</div>
			    				</div>
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="password" name="user[password_confirmation]" id="user_password_confirmation" class="form-control input-sm" placeholder="Confirm Password" required>
			    					</div>
			    				</div>
			    			</div>
			    			
			    			<input type="submit" name="commit" value="Register" class="btn btn-info btn-block">
			    		
			    		</form>
			    	</div>
	    		</div>
    		</div>
    	</div>
    </div>
<% end %>